# Generated by Django 5.2.6 on 2025-09-09 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_email_verification_token_user_is_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('booking_reminder', 'Booking Reminder'), ('booking_cancelled', 'Booking Cancelled'), ('booking_expiry', 'Booking Expiry'), ('lot_full', 'Parking Lot Full'), ('lot_available', 'Parking Available'), ('slot_reserved', 'Slot Reserved'), ('account_update', 'Account Update'), ('payment_confirmation', 'Payment Confirmation'), ('payment_failed', 'Payment Failed'), ('system_alert', 'System Alert'), ('maintenance', 'Maintenance Alert')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
