# Generated by Django 5.2.6 on 2025-09-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pricingrate_booking_extension_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vehicle_has_left',
            field=models.BooleanField(default=False),
        ),
    ]
