# Generated by Django 5.2.6 on 2025-09-12 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_booking_vehicle_has_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('booking_reminder', 'Booking Reminder'), ('booking_cancelled', 'Booking Cancelled'), ('booking_expiry', 'Booking Expiry'), ('booking_update', 'Booking Update'), ('booking_error', 'Booking Error'), ('lot_full', 'Parking Lot Full'), ('lot_available', 'Parking Available'), ('slot_reserved', 'Slot Reserved'), ('account_update', 'Account Update'), ('payment_confirmation', 'Payment Confirmation'), ('payment_failed', 'Payment Failed'), ('payment_receipt', 'Payment Receipt'), ('system_alert', 'System Alert'), ('maintenance', 'Maintenance Alert')], max_length=50),
        ),
        migrations.CreateModel(
            name='DynamicPricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_occupancy', models.IntegerField(default=0, help_text='Minimum occupancy percentage for this rule to apply')),
                ('max_occupancy', models.IntegerField(default=100, help_text='Maximum occupancy percentage for this rule to apply')),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier to apply to the base price', max_digits=4)),
                ('priority', models.IntegerField(default=0, help_text='Priority when multiple rules match')),
                ('applies_weekdays', models.BooleanField(default=True)),
                ('applies_weekends', models.BooleanField(default=True)),
                ('start_hour', models.IntegerField(default=0, help_text='Hour of day when rule starts (0-23)')),
                ('end_hour', models.IntegerField(default=23, help_text='Hour of day when rule ends (0-23)')),
                ('is_active', models.BooleanField(default=True)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='api.parkinglot')),
            ],
            options={
                'ordering': ['-priority', 'min_occupancy'],
            },
        ),
    ]
