# Generated by Django 4.1.13 on 2025-09-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_notification_additional_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('suv', 'SUV'), ('bike', 'Bike'), ('truck', 'Truck'), ('any', 'Any Vehicle')], default='any', help_text='Type of vehicle this slot is designated for', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('suv', 'SUV'), ('bike', 'Bike'), ('truck', 'Truck')], max_length=10),
        ),
    ]
