# Generated by Django 4.1.13 on 2025-10-19 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_booking_actual_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='height_cm',
            field=models.IntegerField(default=200, help_text='Height of parking slot in centimeters'),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='length_cm',
            field=models.IntegerField(default=500, help_text='Length of parking slot in centimeters'),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='width_cm',
            field=models.IntegerField(default=300, help_text='Width of parking slot in centimeters'),
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username used in login attempt', max_length=150)),
                ('user_role', models.CharField(blank=True, help_text='User role at time of access', max_length=10)),
                ('login_timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the user logged in or attempted to log in')),
                ('logout_timestamp', models.DateTimeField(blank=True, help_text='When the user logged out', null=True)),
                ('session_duration', models.DurationField(blank=True, help_text='Duration of the session (logout_timestamp - login_timestamp)', null=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='IP address of the user')),
                ('user_agent', models.TextField(blank=True, help_text='Full user agent string from the browser')),
                ('location_city', models.CharField(blank=True, help_text='City derived from IP address', max_length=100, null=True)),
                ('location_country', models.CharField(blank=True, help_text='Country derived from IP address', max_length=100, null=True)),
                ('location_coordinates', models.JSONField(blank=True, help_text='Latitude and longitude as {lat: x.xxx, lon: y.yyy}', null=True)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', help_text='Type of device used', max_length=20)),
                ('browser', models.CharField(blank=True, help_text='Browser name and version', max_length=50)),
                ('operating_system', models.CharField(blank=True, help_text='Operating system name and version', max_length=50)),
                ('status', models.CharField(choices=[('success', 'Login Success'), ('failed', 'Login Failed'), ('locked', 'Account Locked'), ('logout', 'Logged Out')], db_index=True, help_text='Status of the access attempt', max_length=20)),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for failed login (e.g., invalid password, account locked)', null=True)),
                ('is_suspicious', models.BooleanField(db_index=True, default=False, help_text='Flag for suspicious activity (rapid login attempts, unusual location, etc.)')),
                ('user', models.ForeignKey(blank=True, help_text='User who accessed the system (null for failed login attempts)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Log',
                'verbose_name_plural': 'Access Logs',
                'ordering': ['-login_timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['-login_timestamp'], name='api_accessl_login_t_de45be_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['user', '-login_timestamp'], name='api_accessl_user_id_8cb439_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['ip_address', '-login_timestamp'], name='api_accessl_ip_addr_a18f22_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['status', '-login_timestamp'], name='api_accessl_status_df6cea_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['is_suspicious', '-login_timestamp'], name='api_accessl_is_susp_0d5d48_idx'),
        ),
    ]
