# Generated by Django migration

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_parkingslot_height_cm_parkingslot_length_cm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, help_text='Username at time of login attempt', max_length=150)),
                ('email', models.EmailField(blank=True, help_text='Email used for login attempt', max_length=254)),
                ('role', models.CharField(blank=True, help_text='User role (customer/admin/security)', max_length=10)),
                ('login_timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('logout_timestamp', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of login attempt', null=True)),
                ('location_city', models.CharField(blank=True, help_text='City from IP geolocation', max_length=100)),
                ('location_country', models.CharField(blank=True, help_text='Country from IP geolocation', max_length=100)),
                ('latitude', models.FloatField(blank=True, help_text='GPS latitude (if available)', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='GPS longitude (if available)', null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('locked', 'Account Locked')], db_index=True, default='success', max_length=10)),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for failed login')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device user agent string')),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('operating_system', models.CharField(blank=True, max_length=50)),
                ('session_id', models.CharField(blank=True, help_text='Session ID for logout tracking', max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Log',
                'verbose_name_plural': 'Access Logs',
                'ordering': ['-login_timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['user', 'login_timestamp'], name='api_accessl_user_id_deef5e_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['status', 'login_timestamp'], name='api_accessl_status_956c41_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['ip_address'], name='api_accessl_ip_addr_248235_idx'),
        ),
    ]
