# Generated by Django 4.1.13 on 2025-10-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_enhance_pricingrate_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingrate',
            options={'ordering': ['-is_default', 'vehicle_type', 'rate_name'], 'verbose_name': 'Pricing Rate', 'verbose_name_plural': 'Pricing Rates'},
        ),
        migrations.AlterField(
            model_name='pricingrate',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per hour in ₹', max_digits=6, null=True),
        ),
    ]
