# Generated by Django 4.1.13 on 2025-10-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_pricingrate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='parking_zone',
            field=models.CharField(choices=[('COLLEGE_PARKING_CENTER', 'College Parking'), ('HOME_PARKING_CENTER', 'Home Parking'), ('METRO_PARKING_CENTER', 'Metro Parking'), ('VIVIVANA_PARKING_CENTER', 'Vivivana Parking')], default='COLLEGE_PARKING_CENTER', help_text='Parking zone/location this slot belongs to', max_length=30),
        ),
    ]
