# Generated by Django 4.1.13 on 2025-10-22 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_parking_zone_to_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonePricingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_zone', models.CharField(choices=[('COLLEGE_PARKING_CENTER', 'College Parking Center'), ('HOME_PARKING_CENTER', 'Home Parking Center'), ('METRO_PARKING_CENTER', 'Metro Parking Center'), ('VIVIVANA_PARKING_CENTER', 'Vivivana Parking Center')], help_text='Parking zone for this rate', max_length=50)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('suv', 'SUV'), ('truck', 'Truck'), ('any', 'Any Vehicle')], help_text='Vehicle type for this rate', max_length=20)),
                ('rate_name', models.CharField(help_text='Display name for this rate', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Hourly parking rate', max_digits=10)),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Daily parking rate (24 hours)', max_digits=10)),
                ('weekend_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Weekend hourly rate (optional, defaults to hourly_rate)', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now, help_text='When this rate becomes effective')),
                ('effective_to', models.DateTimeField(blank=True, help_text='When this rate expires (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_zone_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='zonepricingrate',
            index=models.Index(fields=['parking_zone', 'vehicle_type'], name='api_zonepri_parking_d9bfa4_idx'),
        ),
        migrations.AddIndex(
            model_name='zonepricingrate',
            index=models.Index(fields=['is_active', 'effective_from'], name='api_zonepri_is_acti_29a8c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='zonepricingrate',
            unique_together={('parking_zone', 'vehicle_type', 'is_active')},
        ),
    ]
