# Generated by Django 4.1.13 on 2025-10-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_zonepricingrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='secret_code',
            field=models.CharField(blank=True, db_index=True, help_text='6-digit code given to user at check-in for check-out verification', max_length=6, null=True, unique=True),
        ),
    ]
