# Generated by Django 4.1.13 on 2025-10-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_booking_checkout_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='overstay_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated overstay fee amount', max_digits=8),
        ),
        migrations.AddField(
            model_name='booking',
            name='overstay_paid',
            field=models.BooleanField(default=False, help_text='Whether overstay fee has been paid'),
        ),
        migrations.AddField(
            model_name='booking',
            name='overstay_paid_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when overstay fee was paid', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='overstay_payment_method',
            field=models.CharField(blank=True, help_text='Payment method used for overstay (card, cash, etc)', max_length=20, null=True),
        ),
    ]
